### ISSUE TITLE
Some question to Adult dataset

### ISSUE THREAD

**Issue by wulas09763** [BalticBytes/vertical-federated-learning-kang#1]
Hello, thank you for providing such a good code, but I have a question.

I use Adult dataset in your program, but I have the following errors in pre -processing. Where can I not change it? Thank you.

![螢幕擷取畫面 2022-10-10 145600](https://user-images.githubusercontent.com/77091983/194812237-65a90d7d-7643-4f82-8b41-160d7b6df2df.png)

**Comment by BalticBytes** [comment]
Hello @wulas09763 !

The income column has string values such as ">50k" or "<50k". We can't convert those to integer values, so we convert them to a boolean first.

Anyways, I think you can replace 

https://github.com/BalticBytes/vertical-federated-learning-kang/blob/c55bcc85be82599c476d56de0f6717ab38c4bd72/tf_vertical_FL_train.py#L110

with 

https://github.com/BalticBytes/vertical-federated-learning-kang/blob/c55bcc85be82599c476d56de0f6717ab38c4bd72/torch_vertical_FL_train.py#L62

--- 

Sorry, I skipped adapting `torch_vertical_FL_train.py` because I was working with pytorch.

Hope it helps!

**Comment by wulas09763** [comment]
Thanks for your help, it's works !
